### ISSUE TITLE
Showcase active/active deployment

### ISSUE THREAD

**Issue by jamesfalkner** [RedHat-Middleware-Workshops/dg8-workshop#12]
This is a RFE to add an exercise to demonstrate DG's ability to do active/active deployments (possibly simulated on a single cluster since multi-cluster is difficult to setup). @sshaaf

**Comment by sshaaf** [comment]
Yes, we tried this before with two Openshift clusters. The way it works today is with the Loadbalancers. Should be possible to have two projects to showcase DG in both replicating the caches. Needs a bit more investigation, but certainly an important RFE for the next update if not earlier then the 8.1 release.

**Comment by sshaaf** [comment]
Fixed on ocp 4.7 and 8.2 upgrade.
