### ISSUE TITLE
RFE: write more session data in session externalization lab

### ISSUE THREAD

**Issue by sshaaf** [RedHat-Middleware-Workshops/dg8-workshop#15]
We should add a scenario e.g. shopping cart, to show case the Spring session support. 
Also we should have an remote cache scenario so replicated sessions can be showcased. @danieloh30

**Comment by danieloh30** [comment]
@sshaaf Sure, I'll do it. Do you want to keep the current GUI to show spring session data when we add a new scenario or app's own GUI(i.e. shopping cart swagger UI)?

**Comment by sshaaf** [comment]
Current should be fine, if we take it step by step.
