### ISSUE TITLE
Embedded Cache Lab - onStart method instantiates cache even though it has been Injected earlier

### ISSUE THREAD

**Issue by gbengataylor** [RedHat-Middleware-Workshops/dg8-workshop#4]
In ScoreService.java instructions ask to add
```
    @Inject
    EmbeddedCacheManager cacheManager; 
```

but in the onStart method, it is initialized to DefaultCacheManager
```
    void onStart(@Observes @Priority(value = 1) StartupEvent ev){
       cacheManager = new DefaultCacheManager(); // is this necessary? already injected the embedded cache
```

**Comment by sshaaf** [comment]
Its not injected, so we most likely need to remove the injection.

**Comment by sshaaf** [comment]
The section in question needs more changes to the code. Already working on that, and will add this to the list.

**Comment by sshaaf** [comment]
Thanks!
There will be more changes, coming from this solution repo: https://github.com/sshaaf/dg8-embedded-quarkus
