### ISSUE TITLE
Why do you use Infinispan

### ISSUE THREAD

**Issue by HelloTo4x** [RedHat-Middleware-Workshops/dg8-workshop#51]
Hi, i am reading your project, why do you use Infinispan for caching instead of Redis, can you tell me why you choose it, and the pros and cons of this, thank u so much

**Comment by sshaaf** [comment]
Its an awesome distributed cache software; I saw this great [video]( https://www.youtube.com/watch?v=Kb46QFigx84), and take a look at the [infinispan-tutorials](https://infinispan.org/tutorials/)
