### ISSUE TITLE
Update CodeReady Operator Installation

### ISSUE THREAD

**Issue by sshaaf** [RedHat-Middleware-Workshops/dg8-workshop#7]
Need to update the CodeReady Operator to use SSL by default. 
This is due to issues e.g. cloning of repositories etc.

**Comment by sshaaf** [comment]
@danieloh30 you mentioned some fixes for this? can you elaborate what needs to be done?

**Comment by danieloh30** [comment]
For OCP 4.3, you need to do 2 things below:
1) Set "tlsSupport: true" in devfile. For example in CCN here:
https://github.com/redhat-cop/agnosticd/blob/development/ansible/roles/ocp4-workload-ccnrd/files/codeready_cr.yaml#L13
2) Ask GPTE to set Let's Encrypt as default in the CF order form.

For OCP 4.4+, #1 is already `true` as default so you just need to do #2.

**Comment by sshaaf** [comment]
@danieloh30

**Comment by sshaaf** [comment]
Fixed in agnosticD
